### ISSUE TITLE
unclear in your instructions how to stitch two worlds together

### ISSUE THREAD

**Issue by Mremenar** [hetmankp/mcmerge#10]
Thank you for making this program!
I am unclear in your instructions how to stitch two worlds together: 

3. Run the contour trace phase on the map, for example (use the correct world name for you):
python mcmerge.py trace "%AppData%\.minecraft\saves\World"
This places the file contour.dat in the world directory which will be read when merging.
4. Play some Minecraft to generate the new areas bordering with your old map.
5. Run the merging phase. You can tweak various parameters for the best look. Using the default configuration this will look something like the following (again, make sure you specify the correct world directory):
python mcmerge.py merge "%AppData%\.minecraft\saves\World"
6. Get back into the game and watch the floating debris disappear.
You can repeat steps 4 - 6 as many times as you need as the tool will keep track of which border areas haven't yet been merged because they haven't had new areas generated next to them.

At what point do I identify the second world for stitching together?
Not being a programmer or computer scientist, a program that I could just type in "mcmerge world1 world2" at the command prompt would be ideal.

How do I put the two different worlds together and make one world?

Thanks in advance for your help
M

**Comment by hetmankp** [comment]
Hi. This tool can't stitch two completely independent worlds together. You will need the help of another tool like MCEdit to do that.

First run "mcmerge trace" on world1. Then use MCEdit to stitch in the second world. Finally run "mcmerge merge" on the final result. The mcmerge tool's only real purpose is to remove the jagged cliffs that appears when you put two worlds right next to each other.

The truth is, even then, if you want really good results it's not the easiest tool to work with. The reason is that, first, intelligent merging is difficult and second, I moved on from Minecraft so development on mcmerge stopped.

Good luck.

**Comment by Mremenar** [comment]
Thank you for the response.  I guess I was confused because the title of your GitHub page is "Tool for stitching together Minecraft maps" when it might be more clear if titled "Tool to Remove Shearing from Minecraft Maps."  Thanks again.
